# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Module\ApiIntegration\Service\PlankaApiIntegrator:
        arguments:
            $user: '%env(PLANKA_USER)%'
            $password: '%env(PLANKA_PASSWORD)%'
            $uri: '%env(PLANKA_URI)%'
            $port: '%env(PLANKA_PORT)%'

    App\Module\AutoNumerator\Service\AutoNumerateCardService:
        arguments:
            $boardId: '%env(PLANKA_BOARD_ID)%'